"""A small embedded sample of the names dataset (from karpathy/makemore names.txt).

Used as an offline fallback by labs/common.py when neither ../data/names.txt nor a
network download is available. 250 names is plenty for the labs' quick demos.
"""

NAMES = [
    'aadyant', 'adaiyah', 'adalys', 'adell', 'adelline', 'adhvika',
    'adris', 'aella', 'afra', 'airlie', 'aksh', 'aleck',
    'aleira', 'alexya', 'alfonzo', 'aliyan', 'aliza', 'alvis',
    'amen', 'amit', 'amitai', 'angus', 'ani', 'annora',
    'anton', 'antron', 'anvith', 'areesha', 'arieh', 'artem',
    'asia', 'aslan', 'avarose', 'aveleen', 'avriel', 'avyansh',
    'aylena', 'baelyn', 'baxley', 'bayla', 'bayron', 'bellah',
    'bezaleel', 'blaze', 'bostynn', 'branch', 'braylynn', 'briannah',
    'briela', 'brinsley', 'brixton', 'bryonna', 'buster', 'caliber',
    'camarie', 'camrynn', 'candace', 'carlo', 'cayne', 'cedric',
    'chantz', 'christie', 'claudius', 'cleveland', 'courage', 'dahliah',
    'dannah', 'daraly', 'darson', 'dekai', 'dekari', 'demmi',
    'dena', 'dhalia', 'dillyn', 'dio', 'draylen', 'dyamond',
    'edrick', 'eduardo', 'ehaan', 'eiden', 'elgin', 'eliannah',
    'elior', 'elis', 'emaan', 'emalynn', 'embry', 'esben',
    'esjay', 'estrella', 'evolet', 'fallou', 'fina', 'forest',
    'gabbriella', 'gabino', 'gabriel', 'germany', 'giuliette', 'graesyn',
    'greysin', 'greyson', 'grier', 'hasti', 'hayat', 'haygen',
    'hila', 'hiyab', 'husna', 'ilhan', 'ily', 'ira',
    'iriana', 'issac', 'iyana', 'jabriya', 'jaceion', 'jacie',
    'jacoby', 'jaidin', 'janae', 'jasraj', 'jazelyn', 'jewell',
    'jimmie', 'joycelyn', 'kaegan', 'kahlila', 'kaileen', 'kaileigh',
    'kairyn', 'kaleeya', 'kalilah', 'kalynn', 'kapono', 'karalyn',
    'karsten', 'kassaya', 'kaylib', 'kedan', 'kelley', 'kenedy',
    'keone', 'kesslyn', 'keylan', 'keylee', 'khalani', 'kloee',
    'kopelyn', 'kristi', 'lainey', 'laklynn', 'lavaya', 'layken',
    'leba', 'ledger', 'leighana', 'lianne', 'loryn', 'louella',
    'louka', 'love', 'luma', 'maanya', 'maddyn', 'magdaline',
    'makalah', 'makeda', 'malick', 'marciano', 'maryfrances', 'maxima',
    'mayalee', 'maysa', 'melania', 'micaella', 'millani', 'mirella',
    'muhanad', 'muhib', 'myana', 'nason', 'nelani', 'niyan',
    'nolani', 'oakland', 'orrin', 'osvaldo', 'paetyn', 'pesach',
    'quanah', 'quianna', 'rakari', 'rance', 'rawlins', 'redford',
    'reign', 'rexford', 'rhyland', 'riki', 'rockie', 'romney',
    'rovanio', 'samvel', 'saraiya', 'sayden', 'sayed', 'sensei',
    'sevrin', 'shaheer', 'shamshon', 'skylan', 'slater', 'solenne',
    'sonnie', 'sophiagrace', 'stefaniya', 'stella', 'stevi', 'suleyma',
    'suraiya', 'szymon', 'tannen', 'tevion', 'therin', 'tian',
    'tiger', 'travon', 'tuff', 'tzvi', 'verina', 'welden',
    'xxavier', 'xya', 'yaqoob', 'yarel', 'yetzael', 'yezen',
    'yian', 'yorleny', 'zakia', 'zaydee', 'zayn', 'zeon',
    'zisha', 'zurie', 'zuriel', 'zymere',
]
